# 图像处理服务Kubernetes部署配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-service
  namespace: historical-text
  labels:
    app: image-processing-service
    version: v1.0.0
    component: image-processing
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: image-processing-service
  template:
    metadata:
      labels:
        app: image-processing-service
        version: v1.0.0
        component: image-processing
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8005"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: image-processing-service
        image: image-processing-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8005
          name: http
          protocol: TCP
        env:
        - name: SERVICE_NAME
          value: "image-processing-service"
        - name: PORT
          value: "8005"
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: STORAGE_SERVICE_URL
          value: "http://storage-service:8002"
        - name: TEMP_DIR
          value: "/app/temp"
        - name: UPLOAD_DIR
          value: "/app/uploads"
        - name: MAX_CONCURRENT_TASKS
          value: "20"
        - name: TASK_TIMEOUT
          value: "600"
        - name: OPENCV_THREAD_COUNT
          value: "8"
        - name: TORCH_DEVICE
          value: "cpu"
        resources:
          limits:
            cpu: "2000m"
            memory: "4Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8005
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: temp-storage
          mountPath: /app/temp
        - name: upload-storage
          mountPath: /app/uploads
        - name: logs
          mountPath: /app/logs
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
      volumes:
      - name: temp-storage
        emptyDir:
          sizeLimit: 10Gi
      - name: upload-storage
        emptyDir:
          sizeLimit: 10Gi
      - name: logs
        emptyDir:
          sizeLimit: 1Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: default

---
# Service配置
apiVersion: v1
kind: Service
metadata:
  name: image-processing-service
  namespace: historical-text
  labels:
    app: image-processing-service
    component: image-processing
spec:
  type: ClusterIP
  ports:
  - port: 8005
    targetPort: 8005
    protocol: TCP
    name: http
  selector:
    app: image-processing-service

---
# HorizontalPodAutoscaler配置
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: image-processing-service-hpa
  namespace: historical-text
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-processing-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60