# Consul服务注册与发现 - Kubernetes部署
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: historical-text
  labels:
    app: consul
    component: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
        component: service-discovery
    spec:
      containers:
      - name: consul
        image: consul:1.16
        ports:
        - containerPort: 8500
          name: ui
        - containerPort: 8600
          name: dns
        env:
        - name: CONSUL_BIND_INTERFACE
          value: "eth0"
        - name: CONSUL_CLIENT_INTERFACE  
          value: "eth0"
        command:
        - consul
        - agent
        - -server
        - -bootstrap
        - -ui
        - -node=consul-k8s
        - -client=0.0.0.0
        - -data-dir=/consul/data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: consul-data
          mountPath: /consul/data
        livenessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: consul-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: historical-text
  labels:
    app: consul
spec:
  type: ClusterIP
  ports:
  - port: 8500
    targetPort: 8500
    name: ui
  - port: 8600
    targetPort: 8600
    name: dns
  selector:
    app: consul
---
# Consul UI访问 (开发环境)
apiVersion: v1
kind: Service
metadata:
  name: consul-ui
  namespace: historical-text
spec:
  type: NodePort
  ports:
  - port: 8500
    targetPort: 8500
    nodePort: 30850
  selector:
    app: consul