# Kubernetes命名空间配置
# 历史文本项目微服务架构
apiVersion: v1
kind: Namespace
metadata:
  name: historical-text
  labels:
    name: historical-text
    environment: development
    project: historical-text-processing
---
# 资源配额配置
apiVersion: v1
kind: ResourceQuota
metadata:
  name: historical-text-quota
  namespace: historical-text
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    pods: "50"