# 数据源服务Service配置
apiVersion: v1
kind: Service
metadata:
  name: data-source-service
  namespace: data-source
  labels:
    app.kubernetes.io/name: data-source-service
    app.kubernetes.io/instance: data-source
    app.kubernetes.io/component: service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    consul.hashicorp.com/service-name: "data-source"
    consul.hashicorp.com/service-tags: "api,microservice,python"
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: data-source-service
    app.kubernetes.io/instance: data-source
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 8001
    targetPort: 8001
    protocol: TCP

---
# 用于外部访问的LoadBalancer服务
apiVersion: v1
kind: Service
metadata:
  name: data-source-external
  namespace: data-source
  labels:
    app.kubernetes.io/name: data-source-service
    app.kubernetes.io/instance: data-source
    app.kubernetes.io/component: external-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: data-source-service
    app.kubernetes.io/instance: data-source
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8000
    protocol: TCP

---
# Headless服务用于服务发现
apiVersion: v1
kind: Service
metadata:
  name: data-source-headless
  namespace: data-source
  labels:
    app.kubernetes.io/name: data-source-service
    app.kubernetes.io/instance: data-source
    app.kubernetes.io/component: headless-service
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: data-source-service
    app.kubernetes.io/instance: data-source
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP